// Code generated by protoc-gen-go. DO NOT EDIT.
// source: private/private.proto

package private // import "github.com/chmking/horde/protobuf/private"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import public "github.com/chmking/horde/protobuf/public"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ScaleRequest struct {
	Users                int32    `protobuf:"varint,1,opt,name=Users,proto3" json:"Users,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	Wait                 int64    `protobuf:"varint,3,opt,name=Wait,proto3" json:"Wait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScaleRequest) Reset()         { *m = ScaleRequest{} }
func (m *ScaleRequest) String() string { return proto.CompactTextString(m) }
func (*ScaleRequest) ProtoMessage()    {}
func (*ScaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{0}
}
func (m *ScaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScaleRequest.Unmarshal(m, b)
}
func (m *ScaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScaleRequest.Marshal(b, m, deterministic)
}
func (dst *ScaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScaleRequest.Merge(dst, src)
}
func (m *ScaleRequest) XXX_Size() int {
	return xxx_messageInfo_ScaleRequest.Size(m)
}
func (m *ScaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScaleRequest proto.InternalMessageInfo

func (m *ScaleRequest) GetUsers() int32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *ScaleRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *ScaleRequest) GetWait() int64 {
	if m != nil {
		return m.Wait
	}
	return 0
}

type ScaleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScaleResponse) Reset()         { *m = ScaleResponse{} }
func (m *ScaleResponse) String() string { return proto.CompactTextString(m) }
func (*ScaleResponse) ProtoMessage()    {}
func (*ScaleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{1}
}
func (m *ScaleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScaleResponse.Unmarshal(m, b)
}
func (m *ScaleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScaleResponse.Marshal(b, m, deterministic)
}
func (dst *ScaleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScaleResponse.Merge(dst, src)
}
func (m *ScaleResponse) XXX_Size() int {
	return xxx_messageInfo_ScaleResponse.Size(m)
}
func (m *ScaleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScaleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScaleResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{2}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{3}
}
func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (dst *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(dst, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

type QuitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRequest) Reset()         { *m = QuitRequest{} }
func (m *QuitRequest) String() string { return proto.CompactTextString(m) }
func (*QuitRequest) ProtoMessage()    {}
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{4}
}
func (m *QuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRequest.Unmarshal(m, b)
}
func (m *QuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRequest.Marshal(b, m, deterministic)
}
func (dst *QuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRequest.Merge(dst, src)
}
func (m *QuitRequest) XXX_Size() int {
	return xxx_messageInfo_QuitRequest.Size(m)
}
func (m *QuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRequest proto.InternalMessageInfo

type QuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{5}
}
func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (dst *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(dst, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

type HeartbeatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{6}
}
func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (dst *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(dst, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

type HeartbeatResponse struct {
	Status               public.Status `protobuf:"varint,1,opt,name=Status,proto3,enum=public.Status" json:"Status,omitempty"`
	Results              []*Result     `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{7}
}
func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (dst *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(dst, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetStatus() public.Status {
	if m != nil {
		return m.Status
	}
	return public.Status_STATUS_UNKNOWN
}

func (m *HeartbeatResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type RegisterRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{8}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RegisterRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{9}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type Result struct {
	Millisecond          int64       `protobuf:"varint,1,opt,name=Millisecond,proto3" json:"Millisecond,omitempty"`
	Code                 public.Code `protobuf:"varint,2,opt,name=Code,proto3,enum=public.Code" json:"Code,omitempty"`
	Method               string      `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`
	Path                 string      `protobuf:"bytes,4,opt,name=Path,proto3" json:"Path,omitempty"`
	Latency              int64       `protobuf:"varint,5,opt,name=Latency,proto3" json:"Latency,omitempty"`
	Message              string      `protobuf:"bytes,6,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_private_babcce0cee7ca4c2, []int{10}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetMillisecond() int64 {
	if m != nil {
		return m.Millisecond
	}
	return 0
}

func (m *Result) GetCode() public.Code {
	if m != nil {
		return m.Code
	}
	return public.Code_CODE_SUCCESS
}

func (m *Result) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Result) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Result) GetLatency() int64 {
	if m != nil {
		return m.Latency
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ScaleRequest)(nil), "private.ScaleRequest")
	proto.RegisterType((*ScaleResponse)(nil), "private.ScaleResponse")
	proto.RegisterType((*StopRequest)(nil), "private.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "private.StopResponse")
	proto.RegisterType((*QuitRequest)(nil), "private.QuitRequest")
	proto.RegisterType((*QuitResponse)(nil), "private.QuitResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "private.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "private.HeartbeatResponse")
	proto.RegisterType((*RegisterRequest)(nil), "private.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "private.RegisterResponse")
	proto.RegisterType((*Result)(nil), "private.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Scale(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*ScaleResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Scale(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*ScaleResponse, error) {
	out := new(ScaleResponse)
	err := c.cc.Invoke(ctx, "/private.Agent/Scale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/private.Agent/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error) {
	out := new(QuitResponse)
	err := c.cc.Invoke(ctx, "/private.Agent/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/private.Agent/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Scale(context.Context, *ScaleRequest) (*ScaleResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Quit(context.Context, *QuitRequest) (*QuitResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Scale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Scale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/private.Agent/Scale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Scale(ctx, req.(*ScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/private.Agent/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/private.Agent/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Quit(ctx, req.(*QuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/private.Agent/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "private.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scale",
			Handler:    _Agent_Scale_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Agent_Stop_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _Agent_Quit_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Agent_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private/private.proto",
}

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/private.Manager/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/private.Manager/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "private.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Manager_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private/private.proto",
}

func init() { proto.RegisterFile("private/private.proto", fileDescriptor_private_babcce0cee7ca4c2) }

var fileDescriptor_private_babcce0cee7ca4c2 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x9b, 0x2f, 0x32, 0x49, 0x13, 0x18, 0x9a, 0xca, 0xf5, 0xc9, 0xca, 0x01, 0xa5, 0x42,
	0x4a, 0xa4, 0x20, 0x24, 0x38, 0x16, 0x38, 0xf4, 0x90, 0x48, 0xb0, 0x11, 0x42, 0xe2, 0xb6, 0x76,
	0xb6, 0xb6, 0x85, 0xeb, 0x35, 0xde, 0x31, 0x12, 0xff, 0x89, 0xbf, 0xc7, 0xbd, 0xf2, 0x7e, 0x24,
	0x6e, 0xd4, 0xd3, 0xce, 0xbc, 0x37, 0x33, 0x3b, 0x33, 0xfb, 0x16, 0x66, 0x65, 0x95, 0xfd, 0xe1,
	0x24, 0x56, 0xf6, 0x5c, 0x96, 0x95, 0x24, 0x89, 0x03, 0xeb, 0x06, 0xaf, 0xcb, 0x3a, 0xca, 0xb3,
	0x78, 0x65, 0x0e, 0xc3, 0xce, 0x37, 0x30, 0xde, 0xc5, 0x3c, 0x17, 0x4c, 0xfc, 0xae, 0x85, 0x22,
	0xbc, 0x84, 0xde, 0x77, 0x25, 0x2a, 0xe5, 0x7b, 0xa1, 0xb7, 0xe8, 0x31, 0xe3, 0x20, 0x42, 0x97,
	0x71, 0x12, 0xfe, 0x79, 0xe8, 0x2d, 0x3c, 0xa6, 0xed, 0x06, 0xfb, 0xc1, 0x33, 0xf2, 0x3b, 0xa1,
	0xb7, 0xe8, 0x30, 0x6d, 0xcf, 0xa7, 0x70, 0x61, 0xab, 0xa9, 0x52, 0x16, 0x4a, 0xcc, 0x2f, 0x60,
	0xb4, 0x23, 0x59, 0xda, 0xea, 0xf3, 0x09, 0x8c, 0x8d, 0x7b, 0xa4, 0xbf, 0xd5, 0x19, 0xb5, 0x68,
	0xe3, 0x5a, 0x1a, 0xe1, 0xe5, 0x9d, 0xe0, 0x15, 0x45, 0x82, 0x1f, 0x62, 0xee, 0xe1, 0x55, 0x0b,
	0x33, 0x81, 0xf8, 0x06, 0xfa, 0x3b, 0xe2, 0x54, 0x9b, 0xb6, 0x27, 0xeb, 0xc9, 0xd2, 0x0e, 0x69,
	0x50, 0x66, 0x59, 0xbc, 0x81, 0x01, 0x13, 0xaa, 0xce, 0x49, 0xf9, 0xe7, 0x61, 0x67, 0x31, 0x5a,
	0x4f, 0x97, 0x6e, 0x59, 0x06, 0x67, 0x8e, 0x9f, 0x7f, 0x84, 0x29, 0x13, 0x49, 0xa6, 0x48, 0x54,
	0x6e, 0x37, 0x08, 0xdd, 0x3b, 0xa9, 0x48, 0xdf, 0x31, 0x64, 0xda, 0x6e, 0xb0, 0xaf, 0xb2, 0x22,
	0xbd, 0x99, 0x21, 0xd3, 0x76, 0xd3, 0xf6, 0x31, 0xd5, 0x8e, 0xf2, 0xcf, 0x83, 0xbe, 0x29, 0x8d,
	0x21, 0x8c, 0xb6, 0x59, 0x9e, 0x67, 0x4a, 0xc4, 0xb2, 0xd8, 0xeb, 0x6a, 0x1d, 0xd6, 0x86, 0x30,
	0x84, 0xee, 0x67, 0xb9, 0x37, 0xeb, 0x9e, 0xac, 0xc7, 0x6e, 0x98, 0x06, 0x63, 0x9a, 0xc1, 0x2b,
	0xe8, 0x6f, 0x05, 0xa5, 0x72, 0xaf, 0xd7, 0x3f, 0x64, 0xd6, 0xd3, 0xed, 0x70, 0x4a, 0xfd, 0xae,
	0x6d, 0x87, 0x53, 0x8a, 0x3e, 0x0c, 0x36, 0x9c, 0x44, 0x11, 0xff, 0xf5, 0x7b, 0xfa, 0x2e, 0xe7,
	0x36, 0xcc, 0x56, 0x28, 0xc5, 0x13, 0xe1, 0xf7, 0x75, 0x82, 0x73, 0xd7, 0xff, 0x3d, 0xe8, 0xdd,
	0x26, 0xa2, 0x20, 0xfc, 0x00, 0x3d, 0xfd, 0xa4, 0x38, 0x3b, 0xac, 0xaa, 0x2d, 0x98, 0xe0, 0xea,
	0x14, 0xb6, 0x03, 0x9f, 0xe1, 0x7b, 0xe8, 0x36, 0x8f, 0x8d, 0x97, 0xc7, 0x88, 0xa3, 0x14, 0x82,
	0xd9, 0x09, 0xda, 0x4e, 0x6b, 0x44, 0xd0, 0x4a, 0x6b, 0x49, 0xa4, 0x95, 0xf6, 0x44, 0x29, 0x67,
	0xf8, 0x05, 0x86, 0x07, 0x5d, 0xe0, 0xf5, 0x21, 0xea, 0x54, 0x3f, 0x41, 0xf0, 0x1c, 0xe5, 0xaa,
	0xac, 0x37, 0x30, 0xd8, 0xf2, 0x82, 0x27, 0xa2, 0xc2, 0x5b, 0x78, 0xe1, 0x5e, 0x11, 0xfd, 0x96,
	0x4c, 0x9e, 0x68, 0x22, 0xb8, 0x7e, 0x86, 0x71, 0xd5, 0x3e, 0xbd, 0xfd, 0x79, 0x93, 0x64, 0x94,
	0xd6, 0xd1, 0x32, 0x96, 0x0f, 0xab, 0x38, 0x7d, 0xf8, 0x95, 0x15, 0xc9, 0x2a, 0x95, 0xd5, 0xbe,
	0xf9, 0xa4, 0x92, 0x64, 0x54, 0xdf, 0xbb, 0xdf, 0x1a, 0xf5, 0x35, 0xf2, 0xee, 0x31, 0x00, 0x00,
	0xff, 0xff, 0x85, 0xc0, 0xfe, 0xab, 0xc7, 0x03, 0x00, 0x00,
}
