language: go

go:
  - 1.12.x
env:
  - GO111MODULE=on
  - secure: "IG3Y8uAHcG4lsgTRlJTxS45/T2aF5B+GFAgIX4IFg2sj8ZWyy9hoFmJyy+fzO0sIR7doknTW7pVB5XK7wk5IGTgHCNXULwFjMHxHMYPw3w6A8C5E+S6RcvGeup3fFkrM6IVLxt0B/Y+X92lDU3rMK+rkjwiQxc6bMjOAS2ekU5QGGiSL3dX+1Wo15bs1G6xXp+bwNE35iurySHBliv/NMKefor1MogddnV7CV3yoHEUFLUE3iqZJWbLOkuNwOL/n4y2cEBaljHhGXNxpUQN2xELrzvepm99kDXjSC6Woi8P7xQ5Uc1Sn1H+Yyqk8ORrJioWeRIP2bSnpMx4yKiugUmASHc+2BRRvJHywRUxW7uqNtN4o5akaCGbiSW0JKB6LFgQdqRFeHslgkDQDhCAaPNgMKzYlLy8HgAKUFFBbo2bdRryRONQqW56KzbiRienwcnFVtorxYPrF+5b3k4RzQ+teF85824+JlRzB37oMqUhEXzFpSDF7BVGEpnkksRKQICbi1zZ1LAfd+me5dJPpE5T78IcGZKhWRb7J/Gji8dDAjEDt/vAZYb7ZTODUsnFc0t6GUUNj1GX2q/xItlMsEXxHhhqyVA4bNJQ70h0T0NihGyqqE6bqwD9HMoUy9/TGD8RboKFKfQV5MFphOKuWSUai81doBcAGd6YkSyD+2TY="

before_script:
  - GO111MODULE=off go get github.com/onsi/ginkgo/ginkgo
  - GO111MODULE=off go get github.com/onsi/gomega/...
  - GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - GO111MODULE=off go get github.com/mattn/goveralls
script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --compilers=2
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
