language: go

go:
  - 1.12.x
env:
  - GO111MODULE=on

before_script:
  - GO111MODULE=off go get github.com/onsi/ginkgo/ginkgo
  - GO111MODULE=off go get github.com/onsi/gomega/...
script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
