// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goteem.proto

package goteem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TeemRequest struct {
	Users                int32    `protobuf:"varint,1,opt,name=Users,proto3" json:"Users,omitempty"`
	Rate                 float32  `protobuf:"fixed32,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeemRequest) Reset()         { *m = TeemRequest{} }
func (m *TeemRequest) String() string { return proto.CompactTextString(m) }
func (*TeemRequest) ProtoMessage()    {}
func (*TeemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_goteem_4c2f2fadb9124ca9, []int{0}
}
func (m *TeemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeemRequest.Unmarshal(m, b)
}
func (m *TeemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeemRequest.Marshal(b, m, deterministic)
}
func (dst *TeemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeemRequest.Merge(dst, src)
}
func (m *TeemRequest) XXX_Size() int {
	return xxx_messageInfo_TeemRequest.Size(m)
}
func (m *TeemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeemRequest proto.InternalMessageInfo

func (m *TeemRequest) GetUsers() int32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *TeemRequest) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type TeemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeemResponse) Reset()         { *m = TeemResponse{} }
func (m *TeemResponse) String() string { return proto.CompactTextString(m) }
func (*TeemResponse) ProtoMessage()    {}
func (*TeemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_goteem_4c2f2fadb9124ca9, []int{1}
}
func (m *TeemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeemResponse.Unmarshal(m, b)
}
func (m *TeemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeemResponse.Marshal(b, m, deterministic)
}
func (dst *TeemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeemResponse.Merge(dst, src)
}
func (m *TeemResponse) XXX_Size() int {
	return xxx_messageInfo_TeemResponse.Size(m)
}
func (m *TeemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeemResponse proto.InternalMessageInfo

type QuitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRequest) Reset()         { *m = QuitRequest{} }
func (m *QuitRequest) String() string { return proto.CompactTextString(m) }
func (*QuitRequest) ProtoMessage()    {}
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_goteem_4c2f2fadb9124ca9, []int{2}
}
func (m *QuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRequest.Unmarshal(m, b)
}
func (m *QuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRequest.Marshal(b, m, deterministic)
}
func (dst *QuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRequest.Merge(dst, src)
}
func (m *QuitRequest) XXX_Size() int {
	return xxx_messageInfo_QuitRequest.Size(m)
}
func (m *QuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRequest proto.InternalMessageInfo

type QuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_goteem_4c2f2fadb9124ca9, []int{3}
}
func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (dst *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(dst, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TeemRequest)(nil), "goteem.TeemRequest")
	proto.RegisterType((*TeemResponse)(nil), "goteem.TeemResponse")
	proto.RegisterType((*QuitRequest)(nil), "goteem.QuitRequest")
	proto.RegisterType((*QuitResponse)(nil), "goteem.QuitResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Teem(ctx context.Context, in *TeemRequest, opts ...grpc.CallOption) (*TeemResponse, error)
	Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Teem(ctx context.Context, in *TeemRequest, opts ...grpc.CallOption) (*TeemResponse, error) {
	out := new(TeemResponse)
	err := c.cc.Invoke(ctx, "/goteem.Agent/Teem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error) {
	out := new(QuitResponse)
	err := c.cc.Invoke(ctx, "/goteem.Agent/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Teem(context.Context, *TeemRequest) (*TeemResponse, error)
	Quit(context.Context, *QuitRequest) (*QuitResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Teem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Teem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goteem.Agent/Teem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Teem(ctx, req.(*TeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goteem.Agent/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Quit(ctx, req.(*QuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goteem.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Teem",
			Handler:    _Agent_Teem_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _Agent_Quit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goteem.proto",
}

func init() { proto.RegisterFile("goteem.proto", fileDescriptor_goteem_4c2f2fadb9124ca9) }

var fileDescriptor_goteem_4c2f2fadb9124ca9 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0x2f, 0x49,
	0x4d, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xcc, 0xb9, 0xb8,
	0x43, 0x52, 0x53, 0x73, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x43,
	0x8b, 0x53, 0x8b, 0x8a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e,
	0x96, 0xa0, 0xc4, 0x92, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xa6, 0x20, 0x30, 0x5b, 0x89, 0x8f,
	0x8b, 0x07, 0xa2, 0xb1, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x89, 0x97, 0x8b, 0x3b, 0xb0, 0x34,
	0xb3, 0x04, 0x6a, 0x10, 0x48, 0x1a, 0xc2, 0x85, 0x48, 0x1b, 0x15, 0x72, 0xb1, 0x3a, 0xa6, 0xa7,
	0xe6, 0x95, 0x08, 0x19, 0x73, 0xb1, 0x80, 0xf4, 0x09, 0x09, 0xeb, 0x41, 0xdd, 0x83, 0x64, 0xbd,
	0x94, 0x08, 0xaa, 0x20, 0xd4, 0x68, 0x06, 0x90, 0x26, 0x90, 0x69, 0x08, 0x4d, 0x48, 0x56, 0x21,
	0x34, 0x21, 0x5b, 0xa8, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0xa9, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x54, 0x56, 0x06, 0xf9, 0x00, 0x00, 0x00,
}
