// Code generated by protoc-gen-go. DO NOT EDIT.
// source: horde.proto

package horde

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartRequest struct {
	Users                int32    `protobuf:"varint,1,opt,name=Users,proto3" json:"Users,omitempty"`
	Rate                 float32  `protobuf:"fixed32,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_42c3d7c9ac0b1b11, []int{0}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetUsers() int32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *StartRequest) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_42c3d7c9ac0b1b11, []int{1}
}
func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (dst *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(dst, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type QuitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRequest) Reset()         { *m = QuitRequest{} }
func (m *QuitRequest) String() string { return proto.CompactTextString(m) }
func (*QuitRequest) ProtoMessage()    {}
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_42c3d7c9ac0b1b11, []int{2}
}
func (m *QuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRequest.Unmarshal(m, b)
}
func (m *QuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRequest.Marshal(b, m, deterministic)
}
func (dst *QuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRequest.Merge(dst, src)
}
func (m *QuitRequest) XXX_Size() int {
	return xxx_messageInfo_QuitRequest.Size(m)
}
func (m *QuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRequest proto.InternalMessageInfo

type QuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_42c3d7c9ac0b1b11, []int{3}
}
func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (dst *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(dst, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartRequest)(nil), "horde.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "horde.StartResponse")
	proto.RegisterType((*QuitRequest)(nil), "horde.QuitRequest")
	proto.RegisterType((*QuitResponse)(nil), "horde.QuitResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/horde.Agent/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error) {
	out := new(QuitResponse)
	err := c.cc.Invoke(ctx, "/horde.Agent/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Quit(context.Context, *QuitRequest) (*QuitResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/horde.Agent/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/horde.Agent/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Quit(ctx, req.(*QuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "horde.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Agent_Start_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _Agent_Quit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "horde.proto",
}

func init() { proto.RegisterFile("horde.proto", fileDescriptor_horde_42c3d7c9ac0b1b11) }

var fileDescriptor_horde_42c3d7c9ac0b1b11 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc8, 0x2f, 0x4a,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x2c, 0xb8, 0x78, 0x82,
	0x4b, 0x12, 0x8b, 0x4a, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x43,
	0x8b, 0x53, 0x8b, 0x8a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e,
	0x96, 0xa0, 0xc4, 0x92, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xa6, 0x20, 0x30, 0x5b, 0x89, 0x9f,
	0x8b, 0x17, 0xaa, 0xb3, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x89, 0x97, 0x8b, 0x3b, 0xb0, 0x34,
	0x13, 0x66, 0x92, 0x12, 0x1f, 0x17, 0x0f, 0x84, 0x0b, 0x91, 0x36, 0x2a, 0xe0, 0x62, 0x75, 0x4c,
	0x4f, 0xcd, 0x2b, 0x11, 0x32, 0xe1, 0x62, 0x05, 0x6b, 0x14, 0x12, 0xd6, 0x83, 0x38, 0x08, 0xd9,
	0x01, 0x52, 0x22, 0xa8, 0x82, 0x50, 0xb3, 0x19, 0x84, 0x0c, 0xb9, 0x58, 0x40, 0xc6, 0x09, 0x09,
	0x41, 0xe5, 0x91, 0xac, 0x92, 0x12, 0x46, 0x11, 0x83, 0x69, 0x49, 0x62, 0x03, 0xfb, 0xd4, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xd9, 0x9b, 0x10, 0xf8, 0x00, 0x00, 0x00,
}
