// Code generated by protoc-gen-go. DO NOT EDIT.
// source: horde.proto

package horde

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_UNKNOWN  Status = 0
	Status_IDLE     Status = 1
	Status_RUNNING  Status = 2
	Status_STOPPING Status = 3
	Status_QUITTING Status = 4
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "IDLE",
	2: "RUNNING",
	3: "STOPPING",
	4: "QUITTING",
}
var Status_value = map[string]int32{
	"UNKNOWN":  0,
	"IDLE":     1,
	"RUNNING":  2,
	"STOPPING": 3,
	"QUITTING": 4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_horde_549f6a99a826f18d, []int{0}
}

type StartRequest struct {
	Users                int32    `protobuf:"varint,1,opt,name=Users,proto3" json:"Users,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	Wait                 int64    `protobuf:"varint,3,opt,name=Wait,proto3" json:"Wait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_549f6a99a826f18d, []int{0}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetUsers() int32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *StartRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *StartRequest) GetWait() int64 {
	if m != nil {
		return m.Wait
	}
	return 0
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_549f6a99a826f18d, []int{1}
}
func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (dst *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(dst, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_549f6a99a826f18d, []int{2}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_549f6a99a826f18d, []int{3}
}
func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (dst *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(dst, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

type QuitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRequest) Reset()         { *m = QuitRequest{} }
func (m *QuitRequest) String() string { return proto.CompactTextString(m) }
func (*QuitRequest) ProtoMessage()    {}
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_549f6a99a826f18d, []int{4}
}
func (m *QuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRequest.Unmarshal(m, b)
}
func (m *QuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRequest.Marshal(b, m, deterministic)
}
func (dst *QuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRequest.Merge(dst, src)
}
func (m *QuitRequest) XXX_Size() int {
	return xxx_messageInfo_QuitRequest.Size(m)
}
func (m *QuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRequest proto.InternalMessageInfo

type QuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_horde_549f6a99a826f18d, []int{5}
}
func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (dst *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(dst, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartRequest)(nil), "horde.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "horde.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "horde.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "horde.StopResponse")
	proto.RegisterType((*QuitRequest)(nil), "horde.QuitRequest")
	proto.RegisterType((*QuitResponse)(nil), "horde.QuitResponse")
	proto.RegisterEnum("horde.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/horde.Agent/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/horde.Agent/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error) {
	out := new(QuitResponse)
	err := c.cc.Invoke(ctx, "/horde.Agent/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Quit(context.Context, *QuitRequest) (*QuitResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/horde.Agent/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/horde.Agent/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/horde.Agent/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Quit(ctx, req.(*QuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "horde.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Agent_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Agent_Stop_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _Agent_Quit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "horde.proto",
}

func init() { proto.RegisterFile("horde.proto", fileDescriptor_horde_549f6a99a826f18d) }

var fileDescriptor_horde_549f6a99a826f18d = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0xd9, 0x02, 0xb5, 0x19, 0x5a, 0x25, 0xd3, 0x1e, 0x48, 0x4f, 0x84, 0x13, 0xf1, 0xd0,
	0xc4, 0x3f, 0x5f, 0xc0, 0x44, 0xa3, 0xc4, 0x66, 0xdb, 0x2e, 0x90, 0x9e, 0x31, 0x6e, 0xb4, 0x97,
	0x82, 0xec, 0xf0, 0x89, 0xfc, 0xa2, 0x66, 0x17, 0x82, 0xdb, 0xdb, 0xfc, 0xde, 0xcb, 0x0c, 0xef,
	0xb1, 0x10, 0x7c, 0xd7, 0xed, 0xa7, 0xdc, 0x34, 0x6d, 0x4d, 0x35, 0xfa, 0x06, 0x92, 0x2d, 0xcc,
	0x73, 0xaa, 0x5a, 0x12, 0xf2, 0xa7, 0x93, 0x8a, 0x70, 0x05, 0x7e, 0xa9, 0x64, 0xab, 0x22, 0x16,
	0xb3, 0xd4, 0x17, 0x3d, 0x20, 0x82, 0x27, 0x2a, 0x92, 0xd1, 0x24, 0x66, 0x29, 0x13, 0x66, 0xd6,
	0xda, 0xb1, 0x3a, 0x51, 0xe4, 0xc6, 0x2c, 0x75, 0x85, 0x99, 0x93, 0x1b, 0x58, 0x0c, 0xd7, 0x54,
	0x53, 0x9f, 0x95, 0x4c, 0x16, 0x10, 0xe4, 0x54, 0x37, 0xc3, 0xf5, 0xe4, 0x5a, 0x7f, 0x4d, 0xe3,
	0xbf, 0x7d, 0xe8, 0x4e, 0x64, 0xd9, 0x3d, 0xf6, 0xf6, 0xed, 0x1b, 0x4c, 0x73, 0xaa, 0xa8, 0x53,
	0x18, 0xc0, 0x55, 0xc9, 0xdf, 0xf9, 0xee, 0xc8, 0x43, 0x07, 0x67, 0xe0, 0x65, 0xcf, 0xdb, 0x97,
	0x90, 0x69, 0x59, 0x94, 0x9c, 0x67, 0xfc, 0x35, 0x9c, 0xe0, 0x1c, 0x66, 0x79, 0xb1, 0xdb, 0xef,
	0x35, 0xb9, 0x9a, 0x0e, 0x65, 0x56, 0x14, 0x9a, 0xbc, 0xfb, 0x5f, 0x06, 0xfe, 0xd3, 0x97, 0x3c,
	0x13, 0x3e, 0x82, 0x6f, 0x22, 0xe2, 0x72, 0xd3, 0xff, 0x0e, 0xbb, 0xfe, 0x7a, 0x75, 0x29, 0x0e,
	0x31, 0x1d, 0xbc, 0x03, 0x4f, 0x07, 0x47, 0x1c, 0xfd, 0xb1, 0xd4, 0x7a, 0x79, 0xa1, 0xd9, 0x2b,
	0xba, 0xcc, 0xb8, 0x62, 0x15, 0x1d, 0x57, 0xec, 0xb6, 0x89, 0xf3, 0x31, 0x35, 0x4f, 0xf3, 0xf0,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x62, 0xbd, 0x18, 0xa9, 0x01, 0x00, 0x00,
}
