// Code generated by protoc-gen-go. DO NOT EDIT.
// source: public/public.proto

package public // import "github.com/chmking/horde/protobuf/public"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_STATUS_UNKNOWN  Status = 0
	Status_STATUS_IDLE     Status = 1
	Status_STATUS_SCALING  Status = 2
	Status_STATUS_RUNNING  Status = 3
	Status_STATUS_STOPPING Status = 4
	Status_STATUS_QUITTING Status = 5
)

var Status_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "STATUS_IDLE",
	2: "STATUS_SCALING",
	3: "STATUS_RUNNING",
	4: "STATUS_STOPPING",
	5: "STATUS_QUITTING",
}
var Status_value = map[string]int32{
	"STATUS_UNKNOWN":  0,
	"STATUS_IDLE":     1,
	"STATUS_SCALING":  2,
	"STATUS_RUNNING":  3,
	"STATUS_STOPPING": 4,
	"STATUS_QUITTING": 5,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{0}
}

type Health int32

const (
	Health_HEALTH_UNKNOWN   Health = 0
	Health_HEALTH_HEALTHY   Health = 1
	Health_HEALTH_UNHEALTHY Health = 2
)

var Health_name = map[int32]string{
	0: "HEALTH_UNKNOWN",
	1: "HEALTH_HEALTHY",
	2: "HEALTH_UNHEALTHY",
}
var Health_value = map[string]int32{
	"HEALTH_UNKNOWN":   0,
	"HEALTH_HEALTHY":   1,
	"HEALTH_UNHEALTHY": 2,
}

func (x Health) String() string {
	return proto.EnumName(Health_name, int32(x))
}
func (Health) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{1}
}

type Code int32

const (
	Code_CODE_SUCCESS Code = 0
	Code_CODE_ERROR   Code = 1
	Code_CODE_PANIC   Code = 2
)

var Code_name = map[int32]string{
	0: "CODE_SUCCESS",
	1: "CODE_ERROR",
	2: "CODE_PANIC",
}
var Code_value = map[string]int32{
	"CODE_SUCCESS": 0,
	"CODE_ERROR":   1,
	"CODE_PANIC":   2,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}
func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{2}
}

type StartRequest struct {
	Users                int32    `protobuf:"varint,1,opt,name=Users,proto3" json:"Users,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{0}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetUsers() int32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *StartRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{1}
}
func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (dst *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(dst, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{2}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	State                Status   `protobuf:"varint,1,opt,name=State,proto3,enum=public.Status" json:"State,omitempty"`
	Orders               *Orders  `protobuf:"bytes,2,opt,name=Orders,proto3" json:"Orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{3}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetState() Status {
	if m != nil {
		return m.State
	}
	return Status_STATUS_UNKNOWN
}

func (m *StatusResponse) GetOrders() *Orders {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Orders struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Rate                 float64  `protobuf:"fixed64,3,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Orders) Reset()         { *m = Orders{} }
func (m *Orders) String() string { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()    {}
func (*Orders) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{4}
}
func (m *Orders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orders.Unmarshal(m, b)
}
func (m *Orders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orders.Marshal(b, m, deterministic)
}
func (dst *Orders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orders.Merge(dst, src)
}
func (m *Orders) XXX_Size() int {
	return xxx_messageInfo_Orders.Size(m)
}
func (m *Orders) XXX_DiscardUnknown() {
	xxx_messageInfo_Orders.DiscardUnknown(m)
}

var xxx_messageInfo_Orders proto.InternalMessageInfo

func (m *Orders) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Orders) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Orders) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{5}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{6}
}
func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (dst *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(dst, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

type QuitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRequest) Reset()         { *m = QuitRequest{} }
func (m *QuitRequest) String() string { return proto.CompactTextString(m) }
func (*QuitRequest) ProtoMessage()    {}
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{7}
}
func (m *QuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRequest.Unmarshal(m, b)
}
func (m *QuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRequest.Marshal(b, m, deterministic)
}
func (dst *QuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRequest.Merge(dst, src)
}
func (m *QuitRequest) XXX_Size() int {
	return xxx_messageInfo_QuitRequest.Size(m)
}
func (m *QuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRequest proto.InternalMessageInfo

type QuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_92392055cc454af4, []int{8}
}
func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (dst *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(dst, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartRequest)(nil), "public.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "public.StartResponse")
	proto.RegisterType((*StatusRequest)(nil), "public.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "public.StatusResponse")
	proto.RegisterType((*Orders)(nil), "public.Orders")
	proto.RegisterType((*StopRequest)(nil), "public.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "public.StopResponse")
	proto.RegisterType((*QuitRequest)(nil), "public.QuitRequest")
	proto.RegisterType((*QuitResponse)(nil), "public.QuitResponse")
	proto.RegisterEnum("public.Status", Status_name, Status_value)
	proto.RegisterEnum("public.Health", Health_name, Health_value)
	proto.RegisterEnum("public.Code", Code_name, Code_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/public.Manager/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/public.Manager/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/public.Manager/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*QuitResponse, error) {
	out := new(QuitResponse)
	err := c.cc.Invoke(ctx, "/public.Manager/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Quit(context.Context, *QuitRequest) (*QuitResponse, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.Manager/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.Manager/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.Manager/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.Manager/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Quit(ctx, req.(*QuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "public.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Manager_Start_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Manager_Status_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Manager_Stop_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _Manager_Quit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/public.proto",
}

func init() { proto.RegisterFile("public/public.proto", fileDescriptor_public_92392055cc454af4) }

var fileDescriptor_public_92392055cc454af4 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x86, 0x0d, 0x31, 0x54, 0x1d, 0xc7, 0x18, 0x8d, 0x9d, 0x2a, 0xca, 0x29, 0x42, 0x55, 0x65,
	0xf9, 0x60, 0x4b, 0x89, 0x54, 0xa5, 0x47, 0x87, 0xd0, 0x1a, 0xd5, 0x05, 0x67, 0x01, 0x55, 0xed,
	0xa1, 0x11, 0x36, 0xd4, 0xb6, 0x9a, 0x18, 0x17, 0x96, 0x73, 0xdf, 0xb6, 0xcf, 0x51, 0x2d, 0xbb,
	0xc0, 0xd6, 0x27, 0x3c, 0xdf, 0xfc, 0x33, 0x9e, 0xd9, 0x7f, 0x17, 0x86, 0xc7, 0x72, 0xfd, 0xbc,
	0xdf, 0xcc, 0xf8, 0x67, 0x7a, 0xcc, 0x33, 0x9a, 0xa1, 0xce, 0x23, 0xeb, 0x0e, 0xce, 0x03, 0x1a,
	0xe7, 0x94, 0xa4, 0xbf, 0xcb, 0xb4, 0xa0, 0x38, 0x02, 0x2d, 0x2a, 0xd2, 0xbc, 0xb8, 0x54, 0xae,
	0x95, 0xb1, 0x46, 0x78, 0x80, 0x08, 0x5d, 0x12, 0xd3, 0xf4, 0x52, 0xbd, 0x56, 0xc6, 0x0a, 0xa9,
	0x7e, 0x5b, 0x03, 0xe8, 0x8b, 0xca, 0xe2, 0x98, 0x1d, 0x8a, 0x1a, 0xd0, 0xb2, 0x10, 0xbd, 0xac,
	0x1f, 0x60, 0xd4, 0x80, 0x4b, 0xf0, 0x2d, 0x68, 0x8c, 0xa4, 0x55, 0x77, 0xe3, 0xc6, 0x98, 0x8a,
	0x99, 0x84, 0x8c, 0x27, 0xf1, 0x1d, 0xe8, 0x7e, 0x9e, 0xb0, 0x21, 0xd8, 0xff, 0xf5, 0x5a, 0x19,
	0xa7, 0x44, 0x64, 0xad, 0xfb, 0x5a, 0x87, 0x06, 0xa8, 0x6e, 0x52, 0x35, 0x7d, 0x4d, 0x54, 0x37,
	0x61, 0x5b, 0xd8, 0x59, 0x79, 0xa0, 0x55, 0x03, 0x8d, 0xf0, 0xa0, 0xd9, 0xe2, 0x4c, 0xda, 0xa2,
	0x0f, 0xbd, 0x80, 0x66, 0xc7, 0x7a, 0x64, 0x83, 0x1d, 0x07, 0x0b, 0xc5, 0x4e, 0x7d, 0xe8, 0x3d,
	0x96, 0x7b, 0x2a, 0xa5, 0x79, 0xc8, 0xd3, 0x93, 0x3f, 0xa0, 0xf3, 0xd1, 0x11, 0xc1, 0x08, 0xc2,
	0x79, 0x18, 0x05, 0x4f, 0x91, 0xf7, 0xd9, 0xf3, 0xbf, 0x7a, 0x66, 0x07, 0x07, 0xd0, 0x13, 0xcc,
	0x7d, 0x58, 0x3a, 0xa6, 0x22, 0x89, 0x02, 0x7b, 0xbe, 0x74, 0xbd, 0x4f, 0xa6, 0x2a, 0x31, 0x12,
	0x79, 0x1e, 0x63, 0x67, 0x38, 0x84, 0x41, 0xad, 0x0b, 0xfd, 0xd5, 0x8a, 0xc1, 0xae, 0x04, 0x1f,
	0x23, 0x37, 0x0c, 0x19, 0xd4, 0x26, 0x1f, 0x41, 0x5f, 0xa4, 0xf1, 0x33, 0xdd, 0xb1, 0x3e, 0x0b,
	0x67, 0xbe, 0x0c, 0x17, 0xd2, 0x00, 0x2d, 0xe3, 0x9f, 0x6f, 0xa6, 0x82, 0x23, 0x30, 0x1b, 0x5d,
	0x4d, 0xd5, 0xc9, 0x1d, 0x74, 0xed, 0x2c, 0x49, 0xd1, 0x84, 0x73, 0xdb, 0x7f, 0x70, 0x9e, 0x82,
	0xc8, 0xb6, 0x9d, 0x20, 0x30, 0x3b, 0x68, 0x00, 0x54, 0xc4, 0x21, 0xc4, 0x27, 0xa6, 0xd2, 0xc4,
	0xab, 0xb9, 0xe7, 0xda, 0xa6, 0x7a, 0xf3, 0x57, 0x81, 0x57, 0x5f, 0xe2, 0x43, 0xbc, 0x4d, 0x73,
	0x7c, 0x5f, 0xd9, 0x9b, 0x53, 0x1c, 0x49, 0xc6, 0x36, 0x77, 0xeb, 0xea, 0xe2, 0x84, 0x8a, 0x33,
	0xee, 0xe0, 0x87, 0xe6, 0x18, 0x2f, 0x4e, 0x6e, 0x84, 0xa8, 0x7c, 0x73, 0x8a, 0x9b, 0xd2, 0x5b,
	0xe8, 0x32, 0xc3, 0x70, 0xd8, 0x2a, 0x1a, 0x37, 0xaf, 0x46, 0xff, 0x43, 0xb9, 0x88, 0xd9, 0xd8,
	0x16, 0x49, 0x1e, 0xb7, 0x45, 0xb2, 0xd3, 0x56, 0xe7, 0x7e, 0xf2, 0x7d, 0xbc, 0xdd, 0xd3, 0x5d,
	0xb9, 0x9e, 0x6e, 0xb2, 0x97, 0xd9, 0x66, 0xf7, 0xf2, 0x6b, 0x7f, 0xd8, 0xce, 0x76, 0x59, 0x9e,
	0xa4, 0xb3, 0xea, 0x4d, 0xad, 0xcb, 0x9f, 0xe2, 0x8d, 0xad, 0xf5, 0x0a, 0xdc, 0xfe, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xbd, 0x96, 0x14, 0x53, 0x7b, 0x03, 0x00, 0x00,
}
