// Code generated by protoc-gen-go. DO NOT EDIT.
// source: public/public.proto

package public // import "github.com/chmking/horde/protobuf/public"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_STATUS_UNKNOWN  Status = 0
	Status_STATUS_IDLE     Status = 1
	Status_STATUS_SCALING  Status = 2
	Status_STATUS_RUNNING  Status = 3
	Status_STATUS_STOPPING Status = 4
	Status_STATUS_QUITTING Status = 5
)

var Status_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "STATUS_IDLE",
	2: "STATUS_SCALING",
	3: "STATUS_RUNNING",
	4: "STATUS_STOPPING",
	5: "STATUS_QUITTING",
}
var Status_value = map[string]int32{
	"STATUS_UNKNOWN":  0,
	"STATUS_IDLE":     1,
	"STATUS_SCALING":  2,
	"STATUS_RUNNING":  3,
	"STATUS_STOPPING": 4,
	"STATUS_QUITTING": 5,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{0}
}

type Health int32

const (
	Health_HEALTH_UNKNOWN   Health = 0
	Health_HEALTH_HEALTHY   Health = 1
	Health_HEALTH_UNHEALTHY Health = 2
)

var Health_name = map[int32]string{
	0: "HEALTH_UNKNOWN",
	1: "HEALTH_HEALTHY",
	2: "HEALTH_UNHEALTHY",
}
var Health_value = map[string]int32{
	"HEALTH_UNKNOWN":   0,
	"HEALTH_HEALTHY":   1,
	"HEALTH_UNHEALTHY": 2,
}

func (x Health) String() string {
	return proto.EnumName(Health_name, int32(x))
}
func (Health) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{1}
}

type StartRequest struct {
	Users                int32    `protobuf:"varint,1,opt,name=Users,proto3" json:"Users,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{0}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetUsers() int32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *StartRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{1}
}
func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (dst *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(dst, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{2}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{3}
}
func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (dst *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(dst, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{4}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	Status               Status         `protobuf:"varint,1,opt,name=Status,proto3,enum=public.Status" json:"Status,omitempty"`
	Agents               []*AgentStatus `protobuf:"bytes,2,rep,name=Agents,proto3" json:"Agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{5}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNKNOWN
}

func (m *StatusResponse) GetAgents() []*AgentStatus {
	if m != nil {
		return m.Agents
	}
	return nil
}

type AgentStatus struct {
	Status               Status   `protobuf:"varint,1,opt,name=Status,proto3,enum=public.Status" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentStatus) Reset()         { *m = AgentStatus{} }
func (m *AgentStatus) String() string { return proto.CompactTextString(m) }
func (*AgentStatus) ProtoMessage()    {}
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_public_f8ec6e91692458cc, []int{6}
}
func (m *AgentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentStatus.Unmarshal(m, b)
}
func (m *AgentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentStatus.Marshal(b, m, deterministic)
}
func (dst *AgentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentStatus.Merge(dst, src)
}
func (m *AgentStatus) XXX_Size() int {
	return xxx_messageInfo_AgentStatus.Size(m)
}
func (m *AgentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AgentStatus proto.InternalMessageInfo

func (m *AgentStatus) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNKNOWN
}

func init() {
	proto.RegisterType((*StartRequest)(nil), "public.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "public.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "public.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "public.StopResponse")
	proto.RegisterType((*StatusRequest)(nil), "public.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "public.StatusResponse")
	proto.RegisterType((*AgentStatus)(nil), "public.AgentStatus")
	proto.RegisterEnum("public.Status", Status_name, Status_value)
	proto.RegisterEnum("public.Health", Health_name, Health_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/public.Manager/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/public.Manager/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/public.Manager/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.Manager/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.Manager/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.Manager/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "public.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Manager_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Manager_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Manager_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/public.proto",
}

func init() { proto.RegisterFile("public/public.proto", fileDescriptor_public_f8ec6e91692458cc) }

var fileDescriptor_public_f8ec6e91692458cc = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0xef, 0x93, 0x30,
	0x18, 0xc7, 0x7f, 0xb0, 0x81, 0xc9, 0x83, 0x63, 0xa4, 0x30, 0xb3, 0xec, 0xb4, 0x70, 0x30, 0x64,
	0x26, 0x23, 0xd9, 0xa2, 0xd1, 0x23, 0xea, 0x74, 0x8b, 0x93, 0x4d, 0xfe, 0xc4, 0xe8, 0xc5, 0xc0,
	0xac, 0xb0, 0xb8, 0x01, 0x42, 0x39, 0xfb, 0x9a, 0x7c, 0x87, 0x06, 0xda, 0x32, 0xdc, 0xc9, 0x53,
	0xe9, 0xa7, 0x9f, 0xe7, 0x69, 0xe9, 0xb7, 0xa0, 0x17, 0x75, 0x7c, 0x39, 0x9f, 0x6c, 0x3a, 0x2c,
	0x8b, 0x32, 0x27, 0x39, 0x92, 0xe9, 0xcc, 0x7c, 0x09, 0x8f, 0x7d, 0x12, 0x95, 0xc4, 0xc3, 0xbf,
	0x6a, 0x5c, 0x11, 0x64, 0x80, 0x14, 0x56, 0xb8, 0xac, 0xa6, 0xc2, 0x5c, 0xb0, 0x24, 0x8f, 0x4e,
	0x10, 0x82, 0xa1, 0x17, 0x11, 0x3c, 0x15, 0xe7, 0x82, 0x25, 0x78, 0xed, 0xb7, 0x39, 0x86, 0x11,
	0xab, 0xac, 0x8a, 0x3c, 0xab, 0xb0, 0x39, 0x02, 0xc5, 0x27, 0x79, 0xc1, 0x3a, 0x99, 0x6a, 0xd3,
	0xb9, 0x99, 0xb2, 0x65, 0xea, 0x93, 0xba, 0xe2, 0x02, 0x06, 0x95, 0x03, 0xaa, 0xa0, 0xa7, 0x20,
	0x53, 0xd2, 0xee, 0xae, 0xae, 0xd4, 0x25, 0x3b, 0x33, 0xf3, 0xd8, 0x2a, 0x7a, 0x06, 0xb2, 0x93,
	0xe0, 0x8c, 0x54, 0x53, 0x71, 0x3e, 0xb0, 0x94, 0x95, 0xce, 0xbd, 0x96, 0x72, 0x99, 0x2a, 0xe6,
	0x73, 0x50, 0x7a, 0xf8, 0x7f, 0xf7, 0x58, 0xfc, 0xe6, 0x1e, 0x42, 0xa0, 0xfa, 0x81, 0x13, 0x84,
	0xfe, 0xb7, 0xd0, 0xfd, 0xe0, 0x1e, 0x3e, 0xbb, 0xda, 0x03, 0x1a, 0x83, 0xc2, 0xd8, 0xee, 0xed,
	0x7e, 0xa3, 0x09, 0x3d, 0xc9, 0x7f, 0xe3, 0xec, 0x77, 0xee, 0x7b, 0x4d, 0xec, 0x31, 0x2f, 0x74,
	0xdd, 0x86, 0x0d, 0x90, 0x0e, 0x63, 0xee, 0x05, 0x87, 0xe3, 0xb1, 0x81, 0xc3, 0x1e, 0xfc, 0x14,
	0xee, 0x82, 0xa0, 0x81, 0xd2, 0xe2, 0x1d, 0xc8, 0x5b, 0x1c, 0x5d, 0x48, 0xda, 0xf4, 0xd9, 0x6e,
	0x9c, 0x7d, 0xb0, 0xed, 0x1d, 0xe0, 0xc6, 0xe8, 0xf0, 0x45, 0x13, 0x90, 0x01, 0x5a, 0xe7, 0x71,
	0x2a, 0xae, 0xfe, 0x08, 0xf0, 0xe8, 0x63, 0x94, 0x45, 0x09, 0x2e, 0xd1, 0x0b, 0x90, 0xda, 0xcc,
	0x90, 0xd1, 0xfb, 0xeb, 0x2e, 0xfc, 0xd9, 0xe4, 0x8e, 0xb2, 0xe4, 0x1e, 0xd0, 0x1a, 0x86, 0x4d,
	0x96, 0x48, 0xbf, 0x09, 0x5d, 0xd0, 0x33, 0xe3, 0x5f, 0xd8, 0x15, 0xbd, 0xea, 0x6e, 0x70, 0x72,
	0x77, 0xc7, 0xac, 0xf0, 0xc9, 0x3d, 0xe6, 0xa5, 0xaf, 0x17, 0x5f, 0xad, 0xe4, 0x4c, 0xd2, 0x3a,
	0x5e, 0x9e, 0xf2, 0xab, 0x7d, 0x4a, 0xaf, 0x3f, 0xcf, 0x59, 0x62, 0xa7, 0x79, 0xf9, 0x1d, 0xdb,
	0xed, 0xfb, 0x8d, 0xeb, 0x1f, 0xec, 0x3d, 0xc7, 0x72, 0x0b, 0xd6, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x35, 0xb8, 0x5e, 0xde, 0xe7, 0x02, 0x00, 0x00,
}
